### PR TITLE
Gitmate ack plugin pr open test

### PR DESCRIPTION
**Pull request by newuserfortest**

### CODE REVIEW

**Comment by newuserfortest** [comment]
I ack this c5ecd58 commit

**Comment by newuserfortest** [comment]
unack c5ecd58

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
d0c1905 unack

**Comment by newuserfortest** [comment]
unack d0c1905

**Comment by sils** [comment]
ACK d0c1905

**Comment by newuserfortest** [comment]
unack d0c1905

**Comment by newuserfortest** [comment]
ack c5ecd58

**Comment by newuserfortest** [comment]
ack c5ecd58

**Comment by newuserfortest** [comment]
ack c5ec58

**Comment by newuserfortest** [comment]
unack c5ecd58

**Comment by newuserfortest** [comment]
d0c1905 unack

**Comment by newuserfortest** [comment]
unack d0c1905

**Comment by newuserfortest** [comment]
d0c1905 unack

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
ack d0c1905

**Comment by newuserfortest** [comment]
ack d0c1905

**Pull request closed without merging**
